productSample = [
    "Tôi muốn mua một bó hoa hồng đỏ cho sinh nhật.",
    "Bạn có loại hoa nào phù hợp cho lễ kỷ niệm không?",
    "Tôi cần một giỏ hoa để chúc mừng khai trương.",
    "Có hoa cưới cho cô dâu không?",
    "Hoa nào thích hợp để tặng mẹ vào ngày sinh nhật?",
    "Tôi muốn đặt hoa cho ngày lễ tình nhân, bạn có gợi ý gì không?",
    "Có loại hoa nào để viếng đám tang không?",
    "Tôi cần hoa để tặng mừng tốt nghiệp.",
    "Bạn có thể gợi ý một bó hoa đẹp để tặng người yêu không?",
    "Tôi muốn mua hoa chúc mừng ngày phụ nữ Việt Nam.",
    "Bó hoa nào phù hợp để tặng cho ngày Nhà giáo Việt Nam?",
    "Tôi muốn đặt một lẵng hoa để chúc mừng công ty khai trương.",
    "Bạn có hoa lan để tặng không?",
    "Tôi cần một bó hoa tulip cho lễ kỷ niệm tình yêu.",
    "Hoa nào thích hợp để tặng vào dịp năm mới?",
    "Có hoa gì đặc biệt để tặng cho sinh nhật bé gái không?",
    "Tôi muốn mua một giỏ hoa để tặng bà nhân ngày lễ.",
    "Bạn có thể làm một bó hoa mang phong cách cổ điển không?",
    "Tôi cần hoa để trang trí bàn tiệc cưới, bạn có loại nào phù hợp?",
    "Bạn có hoa để làm quà tặng cho đồng nghiệp không?",
    "Hoa nào đẹp để tặng vợ nhân kỷ niệm ngày cưới?",
    "Tôi cần hoa tươi để trang trí hội trường cho một sự kiện lớn.",
    "Bạn có thể gợi ý bó hoa nào để tặng cho người thân ở bệnh viện không?",
    "Tôi muốn mua một lẵng hoa để tặng ông bà nhân dịp tết.",
    "Có hoa gì để tặng bạn nhân dịp sinh nhật mà không quá cầu kỳ?",
    "Hoa nào phù hợp để chúc mừng bạn mới sinh con?",
    "Tôi cần hoa để tặng trong lễ kỷ niệm 50 năm thành lập công ty.",
    "Bạn có thể làm một bó hoa theo yêu cầu với màu sắc cụ thể không?",
    "Tôi muốn mua một bó hoa sen để tặng cho người lớn tuổi.",
    "Hoa nào phù hợp để tặng trong dịp lễ Phật Đản?"
]

chitchatSample = [
    "Hello shop",
    "Chàp shop",
    "Chào bạn! Hôm nay bạn thế nào?",
    "Bạn có thể kể cho tôi nghe về ngày hôm nay của bạn không?",
    "Bạn có thể giúp tôi thư giãn một chút được không?",
    "Bạn thích thời tiết như thế nào?",
    "Bạn làm việc ở đây bao lâu rồi?",
    "Bạn có thích nói chuyện với khách hàng không?",
    "Có điều gì thú vị bạn muốn chia sẻ không?",
    "Bạn có thể kể về lịch sử của cửa hàng không?",
    "Bạn nghĩ gì về mùa xuân?",
    "Bạn có lời khuyên nào để có một ngày vui vẻ không?",
    "Bạn có thể kể một câu chuyện vui không?",
    "Bạn thích làm gì vào thời gian rảnh?",
    "Bạn có biết món ăn nào ngon gần đây không?",
    "Bạn có sở thích nào đặc biệt không?",
    "Bạn có tin vào may mắn không?",
    "Bạn có thể dạy tôi cách chăm sóc hoa không?",
    "Công việc ở cửa hàng này có thú vị không?",
    "Bạn có gặp khách hàng thú vị nào không?",
    "Bạn thích làm việc một mình hay cùng đồng nghiệp?",
    "Bạn có thể chia sẻ một bí quyết thành công trong cuộc sống không?",
    "Bạn có thói quen nào đặc biệt vào buổi sáng không?",
    "Bạn có thể kể về một kỷ niệm đẹp khi làm việc ở đây không?",
    "Bạn nghĩ gì về việc chăm sóc cây cảnh?",
    "Bạn có thể đề xuất một quyển sách hay để đọc không?",
    "Bạn có thể kể về một khách hàng dễ thương mà bạn đã gặp không?",
    "Bạn có tin vào ý nghĩa của các loài hoa không?",
    "Bạn có thể giúp tôi chọn hoa cho một dịp đặc biệt không?"
]
